pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'akashgupta0408/weather-app'
        AWS_CREDENTIALS = credentials('aws-credentials')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def buildNumber = env.BUILD_NUMBER
                    sh "docker build -t ${DOCKER_IMAGE}:${buildNumber} -f weather_app/Dockerfile weather_app"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
                        sh "docker push ${DOCKER_IMAGE}:${buildNumber}"
                    }
                }
            }
        }
    
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'kubectl config use-context akash@test.us-east-1.eksctl.io'
                    sh "sudo -u jenkins kubectl set image deployment/weather-app weather-app=${DOCKER_IMAGE}:${buildNumber} --record --kubeconfig=/home/akash/.kube/config"
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs for details.'
        }
    }
}
